news_sites:
  eluniversal:
    url: http://www.eluniversal.com
    queries:
      homepage_article_links: 'div > a'
      article_body: '#titulo'
      article_title: '#sumario'
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: 'h2 > a'
      article_body: '#article_header h2'
      article_title: '#article_header h1'